version: '3.4'

services:
  test_api:
    build: 
      context: ./server
    container_name: test_api
    ports:
      - 4200:4051
    env_file:
      - .env.integration
    links:
      - mysql
      - mongodb
    depends_on:
      - mysql
      - mongodb
    volumes:
      - '.:/app'
      - '/app/node_modules'
    networks:
      - sail
    command: npm run dev
  api_test:
    image: ehmrs_test_api:latest
    container_name: api_test
    env_file:
      - .env.integration
    depends_on:
      - mysql
      - test_api
    volumes:
      - '.:/app'
      - '/app/node_modules'
    networks:
      - sail
    command: npm run test