version: '3.4'

services:
  api:
    build: .
    ports: 
      - '4050'
    env_file:
      - server/.env
    links: 
      - mongodb
      - mysql
    depends_on: 
      - mysql
      - mongodb
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    networks: 
      - sail
    restart: always
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '5'
    deploy:
      replicas: 5
    command: 'npm run build && npm run start'
  nginx:
    image: nginx:1.18-alpine
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - api
    networks: 
      - sail
    ports: 
      - '80:80'

networks:
  sail:
    driver: bridge