version: '3.4'

services:
  api:
    build:
      context: ./server
    container_name: api
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - "4050:4050"
    env_file:
      - server/.env
    links:
      - mongodb
      - mysql
    depends_on:
      - mysql
      - mongodb
    volumes:
      - './server:/app'
      - '/app/node_modules'
    networks:
      - sail
    restart: always
    command: npm run dev

  web:
    build:
      context: ./client
    container_name: web
    working_dir: /web
    environment:
      NODE_ENV: development
    ports:
      - "8082:8080"
    expose:
      - 8082
    links:
      - api
      - mongodb
      - mysql
    depends_on:
      - api
      - mysql
      - mongodb
    volumes:
      - './client:/web'
      - '/web/node_modules'
    networks:
      - sail
    restart: always
    command: npm run serve

  nginx:
    image: nginx:1.18-alpine
    container_name: nginx
    volumes:
      - .nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - sail
    ports:
      - '80:80'