version: '3.4'

services:
  api:
    build: .
    ports: 
      - '4050'
    env_file:
      - .env
    links: 
      - mongo
      - mysql
    depends_on: 
      - mysql
      - mongo
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    networks: 
      - sail
    restart: always
    deploy:
      replicas: 5
    command: 'npm run build && npm run start'
  nginx:
    image: nginx:1.18-alpine
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - api
    networks: 
      - sail
    ports: 
      - '80:80'