export default [
  {
    url: '/account/transactions',
    icon: 'fas fa-money-check',
    name: 'Transactions',
  },
  // {
  //   url: '/laboratory/samples-collected',
  //   icon: 'fas fa-newspaper',
  //   name: 'Financial History',
  // },
  {
    url: '/laboratory/verified-results',
    icon: 'fas fa-scroll',
    name: 'Insurance Claims',
  },
  // {
  //   url: '/laboratory/find-results',
  //   icon: 'flaticon2-poll-symbol',
  //   name: 'Transactions',
  // },
  // {
  //   url: '/laboratory/reports',
  //   icon: 'flaticon2-list-1',
  //   name: 'Reports',
  // },
  {
    name: 'Chart of Accounts',
    icon: 'fas fa-book',
    color: 'primary',
    url: '/account/chart-of-accounts',
    description: 'Manage your chart of accounts',
  },
  {
    name: 'Journal Entries',
    icon: 'fas fa-journal-whills',
    color: 'success',
    url: '/account/journal-entries',
    description: 'Create and manage journal entries',
  },
  {
    name: 'Trial Balance',
    icon: 'fas fa-balance-scale',
    color: 'info',
    url: '/account/trial-balance',
    description: 'View trial balance report',
  },
  {
    name: 'Cost Centers',
    icon: 'fas fa-building',
    color: 'warning',
    url: '/account/cost-centers',
    description: 'Manage cost centers',
  },
  {
    name: 'Financial Statements',
    icon: 'fas fa-file-invoice-dollar',
    color: 'danger',
    url: '/account/financial-statements',
    description: 'Generate financial statements',
  },
  {
    name: 'Trend Analysis',
    icon: 'fas fa-chart-line',
    color: 'purple',
    url: '/account/trend-analysis',
    description: 'Analyze financial trends',
  },
  {
    name: 'Custom Reports',
    icon: 'fas fa-chart-bar',
    color: 'teal',
    url: '/account/custom-reports',
    description: 'Create custom financial reports',
  },
];
