<template>
  <div class="bill-management">
    <!-- Header Section -->
    <div class="page-header">
      <div class="header-content">
        <div class="header-left">
          <h1 class="page-title">
            <i class="fas fa-file-invoice-dollar text-primary mr-3"></i>
            Bill Management
          </h1>
          <p class="page-subtitle">Manage clinical bills, auto-generated and manual</p>
        </div>
        <div class="header-actions">
          <!-- <b-button variant="primary" @click="openCreateBillModal">
            <i class="fas fa-plus mr-2"></i>Create New Bill
          </b-button> -->
          <b-button variant="outline-primary" @click="exportBills">
            <i class="fas fa-download mr-2"></i>Export
          </b-button>
          <b-button variant="outline-info" @click="refreshBills">
            <i class="fas fa-sync-alt mr-2"></i>Refresh
          </b-button>
        </div>
      </div>
    </div>

    <!-- Quick Stats -->
    <div class="quick-stats mb-4">
      <div class="row">
        <div class="col-lg-3 col-md-6 mb-3">
          <div class="stat-card bg-gradient-primary">
            <div class="stat-icon">
              <i class="fas fa-file-invoice"></i>
            </div>
            <div class="stat-content text-white">
              <h3 class="text-white">{{ billsStats.totalBills || 0 }}</h3>
              <p class="text-white">Total Bills</p>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-3">
          <div class="stat-card bg-gradient-success">
            <div class="stat-icon">
              <i class="fas fa-money-bill-wave"></i>
            </div>
            <div class="stat-content text-white">
              <h3 class="text-white">{{ formatCurrency(billsStats.totalRevenue || 0) }}</h3>
              <p class="text-white">Total Revenue</p>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-3">
          <div class="stat-card bg-gradient-warning">
            <div class="stat-icon">
              <i class="fas fa-clock"></i>
            </div>
            <div class="stat-content text-white">
              <h3 class="text-white">{{ billsStats.pendingPayments || 0 }}</h3>
              <p class="text-white">Pending Payments</p>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-3">
          <div class="stat-card bg-gradient-info">
            <div class="stat-icon">
              <i class="fas fa-robot"></i>
            </div>
            <div class="stat-content text-white">
              <h3 class="text-white">{{ billsStats.autoGenerated || 0 }}</h3>
              <p class="text-white">Auto-Generated</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Filters Section -->
    <BillFilters :filters="filters" @filters-changed="onFiltersChanged" />

    <!-- Bills Table -->
    <div class="bills-table-section">
      <div class="card">
        <div class="card-body">
          <BillTable
            :bills="bills"
            :loading="isLoading"
            @view-bill="viewBill"
            @edit-bill="editBill"
            @process-payment="processPayment"
            @print-bill="printBill"
            @manage-items="manageItems"
          />

          <!-- Pagination -->
          <div class="pagination-section">
            <b-pagination
              v-model="currentPage"
              :total-rows="totalRows"
              :per-page="perPage"
              @change="onPageChange"
              align="center"
            ></b-pagination>
          </div>
        </div>
      </div>
    </div>

    <!-- Bill Details Modal -->
    <BillDetailsModal
      :bill="selectedBill"
      :show="showBillDetailsModal"
      @update:show="showBillDetailsModal = $event"
      @bill-updated="onBillUpdated"
    />

    <!-- Payment Processing Modal -->
    <PaymentProcessingModal
      :bill="selectedBill"
      :show="showPaymentModal"
      @update:show="showPaymentModal = $event"
      @payment-processed="onPaymentProcessed"
    />

    <!-- Create Bill Modal -->
    <!--    <b-modal-->
    <!--      v-model="showCreateBillModal"-->
    <!--      title="Create New Bill"-->
    <!--      size="xl"-->
    <!--      @ok="createBill"-->
    <!--      @hidden="resetCreateBillForm"-->
    <!--    >-->
    <!--      <b-form>-->
    <!--        &lt;!&ndash; Patient and Visit Selection &ndash;&gt;-->
    <!--        <div class="row">-->
    <!--          <div class="col-md-6">-->
    <!--            <b-form-group label="Patient" label-for="patient-select" required>-->
    <!--              <b-form-select-->
    <!--                id="patient-select"-->
    <!--                v-model="createBillForm.patient_id"-->
    <!--                :options="patientOptions"-->
    <!--                required-->
    <!--                @change="onPatientChange"-->
    <!--              ></b-form-select>-->
    <!--            </b-form-group>-->
    <!--          </div>-->
    <!--          <div class="col-md-6">-->
    <!--            <b-form-group label="Visit" label-for="visit-select" required>-->
    <!--              <b-form-select-->
    <!--                id="visit-select"-->
    <!--                v-model="createBillForm.visit_id"-->
    <!--                :options="visitOptions"-->
    <!--                required-->
    <!--                @change="onVisitChange"-->
    <!--              ></b-form-select>-->
    <!--            </b-form-group>-->
    <!--          </div>-->
    <!--        </div>-->

    <!--        &lt;!&ndash; Billing Details &ndash;&gt;-->
    <!--        <div class="row">-->
    <!--          <div class="col-md-4">-->
    <!--            <b-form-group label="Billing Mode" label-for="billing-mode" required>-->
    <!--              <b-form-select-->
    <!--                id="billing-mode"-->
    <!--                v-model="createBillForm.billing_mode"-->
    <!--                :options="billingModeOptions"-->
    <!--                required-->
    <!--              ></b-form-select>-->
    <!--            </b-form-group>-->
    <!--          </div>-->
    <!--          <div class="col-md-4">-->
    <!--            <b-form-group label="Payment Collection Method" label-for="payment-method" required>-->
    <!--              <b-form-select-->
    <!--                id="payment-method"-->
    <!--                v-model="createBillForm.payment_collection_method"-->
    <!--                :options="paymentCollectionOptions"-->
    <!--                required-->
    <!--              ></b-form-select>-->
    <!--            </b-form-group>-->
    <!--          </div>-->
    <!--          <div class="col-md-4">-->
    <!--            <b-form-group label="Payment Collection Point" label-for="collection-point" required>-->
    <!--              <b-form-select-->
    <!--                id="collection-point"-->
    <!--                v-model="createBillForm.payment_collection_point"-->
    <!--                :options="billingPointOptions"-->
    <!--                required-->
    <!--              ></b-form-select>-->
    <!--            </b-form-group>-->
    <!--          </div>-->
    <!--        </div>-->

    <!--        &lt;!&ndash; Bill Items Section &ndash;&gt;-->
    <!--        <div class="bill-items-section">-->
    <!--          <div class="d-flex justify-content-between align-items-center mb-3">-->
    <!--            <h6>Bill Items</h6>-->
    <!--            <b-button variant="outline-primary" size="sm" @click="addBillItem">-->
    <!--              <i class="fas fa-plus mr-2"></i>Add Item-->
    <!--            </b-button>-->
    <!--          </div>-->

    <!--          <div v-for="(item, index) in createBillForm.items" :key="index" class="bill-item-row">-->
    <!--            <div class="row">-->
    <!--              <div class="col-md-3">-->
    <!--                <b-form-group label="Item Type">-->
    <!--                  <b-form-select-->
    <!--                    v-model="item.item_type"-->
    <!--                    :options="itemTypeOptions"-->
    <!--                    @change="onItemTypeChange(index)"-->
    <!--                  ></b-form-select>-->
    <!--                </b-form-group>-->
    <!--              </div>-->
    <!--              <div class="col-md-3">-->
    <!--                <b-form-group label="Item">-->
    <!--                  <b-form-select-->
    <!--                    v-model="item.item_id"-->
    <!--                    :options="getItemOptions(item.item_type)"-->
    <!--                    @change="onItemChange(index)"-->
    <!--                  ></b-form-select>-->
    <!--                </b-form-group>-->
    <!--              </div>-->
    <!--              <div class="col-md-2">-->
    <!--                <b-form-group label="Quantity">-->
    <!--                  <b-form-input-->
    <!--                    v-model.number="item.quantity"-->
    <!--                    type="number"-->
    <!--                    min="1"-->
    <!--                    @input="calculateItemTotal(index)"-->
    <!--                  ></b-form-input>-->
    <!--                </b-form-group>-->
    <!--              </div>-->
    <!--              <div class="col-md-2">-->
    <!--                <b-form-group label="Unit Price">-->
    <!--                  <b-form-input-->
    <!--                    v-model.number="item.unit_price"-->
    <!--                    type="number"-->
    <!--                    step="0.01"-->
    <!--                    @input="calculateItemTotal(index)"-->
    <!--                  ></b-form-input>-->
    <!--                </b-form-group>-->
    <!--              </div>-->
    <!--              <div class="col-md-2">-->
    <!--                <b-form-group label="Total">-->
    <!--                  <b-form-input-->
    <!--                    v-model="item.total_price"-->
    <!--                    readonly-->
    <!--                    class="text-right"-->
    <!--                  ></b-form-input>-->
    <!--                </b-form-group>-->
    <!--              </div>-->
    <!--            </div>-->
    <!--            <div class="row">-->
    <!--              <div class="col-md-8">-->
    <!--                <b-form-group label="Notes">-->
    <!--                  <b-form-input-->
    <!--                    v-model="item.notes"-->
    <!--                    placeholder="Item description or notes..."-->
    <!--                  ></b-form-input>-->
    <!--                </b-form-group>-->
    <!--              </div>-->
    <!--              <div class="col-md-4">-->
    <!--                <div class="d-flex gap-2 mt-4">-->
    <!--                  <b-button variant="outline-danger" size="sm" @click="removeBillItem(index)">-->
    <!--                    <i class="fas fa-trash"></i>-->
    <!--                  </b-button>-->
    <!--                </div>-->
    <!--              </div>-->
    <!--            </div>-->
    <!--          </div>-->
    <!--        </div>-->

    <!--        &lt;!&ndash; Bill Summary &ndash;&gt;-->
    <!--        <div class="bill-summary">-->
    <!--          <div class="row">-->
    <!--            <div class="col-md-6 offset-md-6">-->
    <!--              <table class="table table-borderless">-->
    <!--                <tr>-->
    <!--                  <td>Subtotal:</td>-->
    <!--                  <td class="text-right">{{ formatCurrency(billSubtotal) }}</td>-->
    <!--                </tr>-->
    <!--                <tr>-->
    <!--                  <td>Discount:</td>-->
    <!--                  <td class="text-right">-->
    <!--                    <b-form-input-->
    <!--                      v-model.number="createBillForm.total_discount"-->
    <!--                      type="number"-->
    <!--                      step="0.01"-->
    <!--                      min="0"-->
    <!--                      @input="calculateBillTotal"-->
    <!--                    ></b-form-input>-->
    <!--                  </td>-->
    <!--                </tr>-->
    <!--                <tr>-->
    <!--                  <td>Tax:</td>-->
    <!--                  <td class="text-right">-->
    <!--                    <b-form-input-->
    <!--                      v-model.number="createBillForm.tax_amount"-->
    <!--                      type="number"-->
    <!--                      step="0.01"-->
    <!--                      min="0"-->
    <!--                      @input="calculateBillTotal"-->
    <!--                    ></b-form-input>-->
    <!--                  </td>-->
    <!--                </tr>-->
    <!--                <tr class="border-top">-->
    <!--                  <td><strong>Total:</strong></td>-->
    <!--                  <td class="text-right">-->
    <!--                    <strong>{{ formatCurrency(createBillForm.final_amount) }}</strong>-->
    <!--                  </td>-->
    <!--                </tr>-->
    <!--              </table>-->
    <!--            </div>-->
    <!--          </div>-->
    <!--        </div>-->

    <!--        &lt;!&ndash; Additional Fields &ndash;&gt;-->
    <!--        <div class="row">-->
    <!--          <div class="col-md-6">-->
    <!--            <b-form-group label="Due Date" required>-->
    <!--              <b-form-input v-model="createBillForm.due_date" type="date" required></b-form-input>-->
    <!--            </b-form-group>-->
    <!--          </div>-->
    <!--          <div class="col-md-6">-->
    <!--            <b-form-group label="Notes">-->
    <!--              <b-form-textarea-->
    <!--                v-model="createBillForm.notes"-->
    <!--                rows="3"-->
    <!--                placeholder="Additional notes for this bill..."-->
    <!--              ></b-form-textarea>-->
    <!--            </b-form-group>-->
    <!--          </div>-->
    <!--        </div>-->
    <!--      </b-form>-->

    <!--      <template #modal-footer>-->
    <!--        <b-button variant="secondary" @click="showCreateBillModal = false">-->
    <!--          Cancel-->
    <!--        </b-button>-->
    <!--        <b-button variant="primary" @click="createBill" :disabled="creating">-->
    <!--          <span v-if="creating"> <i class="fas fa-spinner fa-spin mr-2"></i>Creating... </span>-->
    <!--          <span v-else> <i class="fas fa-save mr-2"></i>Create Bill </span>-->
    <!--        </b-button>-->
    <!--      </template>-->
    <!--    </b-modal>-->
  </div>
</template>

<script>
import BillTable from './components/BillTable.vue';
import BillFilters from './components/BillFilters.vue';
import BillDetailsModal from './components/BillDetailsModal.vue';
import PaymentProcessingModal from './components/PaymentProcessingModal.vue';

export default {
  name: 'BillManagement',
  components: {
    BillTable,
    BillFilters,
    BillDetailsModal,
    PaymentProcessingModal,
  },
  data() {
    return {
      // Filters - Must match backend BillSearchFilters interface
      filters: {
        patient_id: null,
        billing_status: '',
        payment_status: '',
        start_date: '',
        end_date: '',
        min_amount: null,
        max_amount: null,
        billing_mode: '',
        page: 1,
        limit: 10,
      },

      // Bills data
      currentPage: 1,
      perPage: 10,

      // Modal states
      showCreateBillModal: false,
      showBillDetailsModal: false,
      showPaymentModal: false,
      creating: false,

      // Selected bill for modals
      selectedBill: null,

      // Create bill form
      createBillForm: {
        patient_id: null,
        visit_id: null,
        billing_mode: 'CASH',
        payment_collection_method: 'POINT_OF_SERVICE',
        payment_collection_point: 'main-cashier',
        items: [],
        total_discount: 0,
        tax_amount: 0,
        final_amount: 0,
        due_date: '',
        notes: '',
      },

      // Options
      billingModeOptions: [
        { value: 'CASH', text: 'Cash' },
        { value: 'INSURANCE', text: 'Insurance' },
        { value: 'WAIVER', text: 'Waiver' },
        { value: 'OTHER', text: 'Other' },
        { value: 'FREE', text: 'Free' },
        { value: 'WALLET', text: 'Wallet' },
      ],
      paymentCollectionOptions: [
        { value: 'DEPOSIT', text: 'Deposit' },
        { value: 'POINT_OF_SERVICE', text: 'Point of Service' },
        { value: 'INSURANCE_CLAIM', text: 'Insurance Claim' },
        { value: 'MIXED', text: 'Mixed' },
      ],
      billingPointOptions: [
        { value: 'main-cashier', text: 'Main Cashier' },
        { value: 'accounting-office', text: 'Accounting Office' },
        { value: 'emergency-cashier', text: 'Emergency Cashier' },
      ],
      itemTypeOptions: [
        { value: 'DRUG', text: 'Drug' },
        { value: 'TEST', text: 'Test' },
        { value: 'INVESTIGATION', text: 'Investigation' },
        { value: 'SERVICE', text: 'Service' },
        { value: 'ADDITIONAL_ITEM', text: 'Additional Item' },
      ],

      // Data options
      patientOptions: [],
      visitOptions: [],
      itemOptions: {
        DRUG: [],
        TEST: [],
        INVESTIGATION: [],
        SERVICE: [],
        ADDITIONAL_ITEM: [],
      },
    };
  },
  computed: {
    billSubtotal() {
      return this.createBillForm.items.reduce((sum, item) => sum + (item.total_price || 0), 0);
    },
    bills() {
      return this.$store.getters['accounting/getClinicalBills'] || [];
    },
    totalRows() {
      return this.$store.getters['accounting/getClinicalBillsTotal'] || 0;
    },
    isLoading() {
      return this.$store.getters['accounting/loading'];
    },
    error() {
      return this.$store.getters['accounting/error'];
    },
    billsStats() {
      const bills = this.bills;
      return {
        totalBills: bills.length,
        totalRevenue: bills.reduce((sum, bill) => sum + (+bill.final_amount || 0), 0),
        pendingPayments: bills.filter((bill) => bill.payment_status === 'PENDING').length,
        autoGenerated: bills.filter((bill) => bill.is_auto_generated).length,
      };
    },
  },
  async mounted() {
    await this.loadBills();
    // await this.loadOptions();
  },
  methods: {
    async loadBills() {
      try {
        // Map frontend filters to backend expectations
        const params = {
          page: this.currentPage,
          limit: this.perPage,
          patient_id: this.filters.patient_id,
          billing_status: this.filters.billing_status || undefined,
          payment_status: this.filters.payment_status || undefined,
          start_date: this.filters.start_date || undefined,
          end_date: this.filters.end_date || undefined,
          min_amount: this.filters.min_amount || undefined,
          max_amount: this.filters.max_amount || undefined,
          billing_mode: this.filters.billing_mode || undefined,
        };

        // Remove undefined values
        Object.keys(params).forEach((key) => {
          if (params[key] === undefined || params[key] === null || params[key] === '') {
            delete params[key];
          }
        });

        await this.$store.dispatch('accounting/fetchClinicalBills', params);
      } catch (error) {
        console.error('Failed to load bills:', error);
      }
    },

    async refreshBills() {
      this.currentPage = 1;
      await this.loadBills();
    },

    onFiltersChanged(newFilters) {
      // Map frontend filter names to backend expectations
      const mappedFilters = {};

      if (newFilters.patientName) {
        // We need to search for patient ID based on name
        // For now, we'll skip patient filtering until we implement patient search
        console.log('Patient name filtering not yet implemented');
      }

      if (newFilters.billingStatus) {
        mappedFilters.billing_status = newFilters.billingStatus;
      }

      if (newFilters.paymentStatus) {
        mappedFilters.payment_status = newFilters.paymentStatus;
      }

      if (newFilters.dateFrom) {
        mappedFilters.start_date = newFilters.dateFrom;
      }

      if (newFilters.dateTo) {
        mappedFilters.end_date = newFilters.dateTo;
      }

      if (newFilters.amountRange) {
        const parts = newFilters.amountRange.split('-').map((s) => parseFloat(s.trim()));
        if (parts.length === 2 && !isNaN(parts[0]) && !isNaN(parts[1])) {
          mappedFilters.min_amount = parts[0];
          mappedFilters.max_amount = parts[1];
        }
      }

      if (newFilters.billingMode) {
        mappedFilters.billing_mode = newFilters.billingMode;
      }

      this.filters = { ...this.filters, ...mappedFilters };
      this.currentPage = 1;
      this.loadBills();
    },

    async loadOptions() {
      try {
        const patients = await this.$store.dispatch('patient/fetchPatients', {
          currentPage: 1,
          itemsPerPage: 50,
          search: '',
        });
        this.patientOptions = patients.map((patient) => ({
          value: patient.id,
          text: `${patient.firstname} ${patient.lastname} (${patient.hospital_id})`,
        }));

        // Load billing points using Vuex store
        const billingPoints = await this.$store.dispatch('accounting/fetchBillingPoints');
        this.billingPointOptions = billingPoints.map((point) => ({
          value: point.id,
          text: point.name,
        }));

        // Load items for each type using Vuex store
        await this.loadItemOptions();
      } catch (error) {
        console.error('Failed to load options:', error);
      }
    },

    async loadItemOptions() {
      try {
        // Load drugs using Vuex store
        const drugsResponse = await this.$store.dispatch('account/fetchPharmacyDrugs');
        this.itemOptions.DRUG = drugsResponse.map((drug) => ({
          value: drug.id,
          text: drug.name,
          price: drug.price,
        }));

        // Load tests using Vuex store
        const testsResponse = await this.$store.dispatch('account/fetchLaboratoryTests');
        this.itemOptions.TEST = testsResponse.map((test) => ({
          value: test.id,
          text: test.name,
          price: test.price,
        }));

        // Load services using Vuex store
        const servicesResponse = await this.$store.dispatch('account/fetchServices');
        this.itemOptions.SERVICE = servicesResponse.map((service) => ({
          value: service.id,
          text: service.name,
          price: service.price,
        }));

        // Similar for other item types...
      } catch (error) {
        console.error('Failed to load item options:', error);
      }
    },

    formatDate(dateString) {
      return new Date(dateString).toLocaleDateString('en-NG');
    },

    async onPatientChange() {
      this.billForm.visit_id = null;
      this.visitOptions = [];

      if (this.billForm.patient_id) {
        try {
          const visits = await this.$store.dispatch(
            'account/fetchPatientVisits',
            this.billForm.patient_id
          );
          this.visitOptions = visits.map((visit) => ({
            value: visit.id,
            text: `${this.formatDate(visit.date_visit_start)} - ${visit.type}`,
          }));
        } catch (error) {
          console.error('Failed to load visits:', error);
        }
      }
    },

    onVisitChange() {
      // Could load visit-specific data here
    },

    onItemTypeChange(index) {
      const item = this.billForm.items[index];
      item.item_id = null;
      item.unit_price = 0;
      item.total_price = 0;
    },

    onItemChange(index) {
      const item = this.billForm.items[index];
      const selectedItem = this.itemOptions[item.item_type].find((opt) => opt.id === item.item_id);

      if (selectedItem) {
        item.unit_price = selectedItem.price || 0;
        this.calculateItemTotal(index);
      }
    },

    calculateItemTotal(index) {
      const item = this.billForm.items[index];
      item.total_price = (item.quantity || 0) * (item.unit_price || 0);
      this.calculateBillTotal();
    },

    calculateBillTotal() {
      const subtotal = this.billSubtotal;
      const discount = this.billForm.total_discount || 0;
      const tax = this.billForm.tax_amount || 0;
      this.billForm.final_amount = subtotal - discount + tax;
    },

    addBillItem() {
      this.billForm.items.push({
        item_type: 'DRUG',
        item_id: null,
        quantity: 1,
        unit_price: 0,
        total_price: 0,
        notes: '',
      });
    },

    removeBillItem(index) {
      this.billForm.items.splice(index, 1);
      this.calculateBillTotal();
    },

    getItemOptions(itemType) {
      return this.itemOptions[itemType] || [];
    },

    // Modal actions
    openCreateBillModal() {
      this.showCreateBillModal = true;
    },

    viewBill(bill) {
      this.selectedBill = bill;
      this.showBillDetailsModal = true;
    },

    editBill(bill) {
      this.selectedBill = bill;
      this.showBillDetailsModal = true;
    },

    processPayment(bill) {
      this.selectedBill = bill;
      this.showPaymentModal = true;
    },

    printBill() {
      // Implement print functionality
      this.$bvToast.toast('Print functionality coming soon', {
        title: 'Info',
        variant: 'info',
        solid: true,
      });
    },

    manageItems(bill) {
      // Navigate to bill items management page
      this.$router.push({
        name: 'bill-items',
        params: { billId: bill.id },
      });
    },

    async loadBillForEdit(billId) {
      try {
        const bill = await this.$store.dispatch('accounting/getClinicalBillById', billId);

        if (bill) {
          this.billForm = {
            patient_id: bill.patient_id,
            visit_id: bill.visit_id,
            billing_mode: bill.billing_mode,
            payment_collection_method: bill.payment_collection_method,
            payment_collection_point: bill.payment_collection_point,
            items:
              bill.billItems?.map((item) => ({
                item_type: item.item_type,
                item_id: item.item_id,
                quantity: item.quantity,
                unit_price: item.unit_price,
                total_price: item.total_price,
                notes: item.notes,
              })) || [],
            total_discount: bill.total_discount || 0,
            tax_amount: bill.tax_amount || 0,
            final_amount: bill.final_amount,
            due_date: bill.due_date,
            notes: bill.notes,
          };
        }
      } catch (error) {
        console.error('Failed to load bill for edit:', error);
      }
    },

    async saveBill() {
      try {
        this.saving = true;

        let result;
        if (this.isEditing) {
          result = await this.$store.dispatch('account/updateBill', {
            id: this.billForm.id,
            billData: this.billForm,
          });
          if (result.success) {
            this.$bvToast.toast('Bill updated successfully', {
              title: 'Success',
              variant: 'success',
              solid: true,
            });
          }
        } else {
          result = await this.$store.dispatch('account/createBill', this.billForm);
          if (result.success) {
            this.$bvToast.toast('Bill created successfully', {
              title: 'Success',
              variant: 'success',
              solid: true,
            });
          }
        }

        if (result.success) {
          this.showBillModal = false;
          this.resetBillForm();
        } else {
          this.$bvToast.toast(result.error || 'Failed to save bill', {
            title: 'Error',
            variant: 'danger',
            solid: true,
          });
        }
      } catch (error) {
        console.error('Failed to save bill:', error);
        this.$bvToast.toast('Failed to save bill', {
          title: 'Error',
          variant: 'danger',
          solid: true,
        });
      } finally {
        this.saving = false;
      }
    },

    resetBillForm() {
      this.billForm = {
        patient_id: null,
        visit_id: null,
        billing_mode: 'CASH',
        payment_collection_method: 'POINT_OF_SERVICE',
        payment_collection_point: 'main-cashier',
        items: [],
        total_discount: 0,
        tax_amount: 0,
        final_amount: 0,
        due_date: '',
        notes: '',
      };
      this.isEditing = false;
    },

    // Event handlers for modals
    onBillUpdated() {
      // Refresh bills after update
      this.loadBills();
      this.$bvToast.toast('Bill updated successfully', {
        title: 'Success',
        variant: 'success',
        solid: true,
      });
    },

    onPaymentProcessed() {
      // Refresh bills after payment
      this.loadBills();
      this.$bvToast.toast('Payment processed successfully', {
        title: 'Success',
        variant: 'success',
        solid: true,
      });
    },

    // Utility methods
    formatCurrency(amount) {
      return new Intl.NumberFormat('en-NG', {
        style: 'currency',
        currency: 'NGN',
      }).format(amount || 0);
    },

    getBillingStatusVariant(status) {
      const variants = {
        DRAFT: 'secondary',
        PENDING: 'warning',
        APPROVED: 'success',
        REJECTED: 'danger',
      };
      return variants[status] || 'secondary';
    },

    getPaymentStatusVariant(status) {
      const variants = {
        PENDING: 'warning',
        PARTIAL: 'info',
        PAID: 'success',
        CANCELLED: 'danger',
      };
      return variants[status] || 'secondary';
    },

    // Filter methods
    clearFilters() {
      this.filters = {
        patientName: '',
        billingStatus: '',
        paymentStatus: '',
        dateRange: '',
      };
      this.loadBills();
    },

    debounceSearch: debounce(function () {
      this.loadBills();
    }, 500),

    onPageChange(page) {
      this.currentPage = page;
      this.loadBills();
    },

    exportBills() {
      // Implement export functionality
      this.$bvToast.toast('Export functionality coming soon', {
        title: 'Info',
        variant: 'info',
        solid: true,
      });
    },
  },
};

// Debounce utility function
function debounce(func, wait) {
  let timeout;
  return function executedFunction(...args) {
    const later = () => {
      clearTimeout(timeout);
      func(...args);
    };
    clearTimeout(timeout);
    timeout = setTimeout(later, wait);
  };
}
</script>

<style scoped>
.bill-management {
  padding: 2rem;
}

.page-header {
  margin-bottom: 2rem;
}

.header-content {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
}

.header-left {
  flex: 1;
}

.page-title {
  font-size: 2rem;
  font-weight: 600;
  color: #2c3e50;
  margin: 0 0 0.5rem 0;
}

.page-subtitle {
  color: #6c757d;
  margin: 0;
  font-size: 1rem;
}

.header-actions {
  display: flex;
  gap: 1rem;
  flex-shrink: 0;
}

.quick-stats {
  margin-bottom: 2rem;
}

.stat-card {
  background: white;
  border-radius: 12px;
  padding: 1.5rem;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
  display: flex;
  align-items: center;
  gap: 1rem;
  transition: transform 0.2s, box-shadow 0.2s;
}

.stat-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 6px 16px rgba(0, 0, 0, 0.12);
}

.stat-icon {
  width: 50px;
  height: 50px;
  border-radius: 10px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 1.5rem;
  color: white;
  flex-shrink: 0;
}

.stat-content h3 {
  margin: 0 0 0.5rem 0;
  font-weight: 600;
  color: #2c3e50;
  font-size: 1.5rem;
}

.stat-content p {
  margin: 0;
  color: #6c757d;
  font-size: 0.9rem;
}

.filters-section {
  margin-bottom: 2rem;
}

.bills-table-section {
  margin-bottom: 2rem;
}

.patient-info {
  display: flex;
  flex-direction: column;
}

.patient-name {
  font-weight: 600;
  color: #2c3e50;
}

.patient-number {
  color: #6c757d;
}

.amount {
  font-weight: 600;
  color: #28a745;
}

.action-buttons {
  display: flex;
  gap: 0.5rem;
}

.pagination-section {
  margin-top: 2rem;
  display: flex;
  justify-content: center;
}

.bill-items-section {
  margin: 2rem 0;
  padding: 1rem;
  border: 1px solid #e9ecef;
  border-radius: 8px;
  background-color: #f8f9fa;
}

.bill-item-row {
  padding: 1rem;
  margin-bottom: 1rem;
  border: 1px solid #dee2e6;
  border-radius: 6px;
  background-color: white;
}

.bill-summary {
  margin: 2rem 0;
  padding: 1rem;
  border: 1px solid #e9ecef;
  border-radius: 8px;
  background-color: #f8f9fa;
}

/* Gradient Backgrounds */
.bg-gradient-primary {
  background: linear-gradient(135deg, #007bff, #0056b3);
}

.bg-gradient-success {
  background: linear-gradient(135deg, #28a745, #1e7e34);
}

.bg-gradient-warning {
  background: linear-gradient(135deg, #ffc107, #e0a800);
}

.bg-gradient-info {
  background: linear-gradient(135deg, #17a2b8, #138496);
}

@media (max-width: 768px) {
  .bill-management {
    padding: 1rem;
  }

  .header-content {
    flex-direction: column;
    gap: 1rem;
    text-align: center;
  }

  .header-actions {
    flex-wrap: wrap;
    justify-content: center;
  }

  .stat-card {
    padding: 1rem;
  }

  .stat-icon {
    width: 40px;
    height: 40px;
    font-size: 1.25rem;
  }

  .stat-content h3 {
    font-size: 1.25rem;
  }
}
</style>
