export default {
  GlucoseForm: [
    { name: 'Fasting glu.', model: 'fasting_glu', range: '3.9 - 5.8 Mmol/L' },
    { name: 'Random glu.', model: 'random_glu', range: '3.9 - 6.7 Mmol/L' },
    { name: '2hr pp', model: 'two_hour_pp', range: '3.9 - 6.7 Mmol/L' },
    { name: 'Comments', model: 'comments', range: '' },
  ],
  AnalyteForm: [
    { name: 'Urine Protein', model: 'urine_protein', range: '0 - 20 mg/dL' },
    { name: 'CSF Glucose', model: 'csf_glucose', range: '2.5 - 4.4 Mmol/L' },
    { name: 'CSF Protein+', model: 'csf_protein', range: '1.5 - 6.0 g/dL' },
    { name: 'Ascitic Fluid', model: 'ascitic_fluid', range: '2.2 - 3.3 Mmol/L' },
    { name: 'Glucose', model: 'glucose', range: '' },
    { name: 'Ascitic Fluid Total', model: 'ascitic_fluid_total', range: '2.5 - 3.0 g/dL' },
    { name: 'Protein', model: 'protein', range: '' },
    { name: 'CSF Chloride', model: 'csf_chloride', range: '110 - 125 Mmol/L' },
    { name: '24 hour Urine', model: 'twenty_four_hour_urine', range: '20 - 150 mg/24hrs' },
    { name: 'Comments', model: 'comments' },
  ],
  SputumForm: [
    { name: 'Culture', model: 'culture' },
    { name: 'Appearance', model: 'appearance' },
    { name: 'Sputum', model: 'sputum' },
    { name: 'Ciprofloxacin', model: 'ciprofloxacin' },
    { name: 'Rifampicin', model: 'rifampicin' },
    { name: 'Streptomycin', model: 'streptomycin' },
    { name: 'Azithromycin', model: 'azithromycin' },
    { name: 'Amoxicillin', model: 'amoxicillin' },
    { name: 'Erythromycin', model: 'erythromycin' },
    { name: 'Levofloxacin', model: 'levofloxacin' },
    { name: 'Gentamycin', model: 'gentamycin' },
    { name: 'Cefuroxime', model: 'cefuroxime' },
    { name: 'Ofloxacin', model: 'ofloxacin' },
    { name: 'Augmentin', model: 'augmentin' },
    { name: 'Peflacine', model: 'peflacine' },
    { name: 'Ceftazidime', model: 'ceftazidime' },
    { name: 'Ceporex', model: 'ceporex' },
    { name: 'Ceftriaxone', model: 'ceftriaxone' },
    { name: 'Comments', model: 'comments' },
  ],
  DefaultResultForm: [{ name: 'Culture', model: 'result' }],
  LipidProfileForm: [
    { name: 'Chol', model: 'chol', range: '140 - 220 mg/dl' },
    { name: 'VLDL', model: 'vldl', range: '15 - 50 mg/dl' },
    { name: 'HDL', model: 'hdl', range: '35 - 65 mg/dl' },
    { name: 'TG', model: 'tg', range: '60 - 165 mg/dl' },
    { name: 'LDL', model: 'ldl', range: 'less than 130 mg/dl' },
    { name: 'Comments', model: 'comments' },
  ],
  LFTForm: [
    { name: 'AST', model: 'ast', range: '5.0 - 50 IU/L' },
    { name: 'ALT', model: 'alt', range: '5.0 - 46 IU/L' },
    { name: 'ALP', model: 'alp', range: '20 - 147 IU/L' },
    { name: 'TP', model: 'tp', range: '6.2 - 8.0 g/dl' },
    { name: 'ALB', model: 'alb', range: '3.5 - 5.5 g/dl' },
    { name: 'TB', model: 'tb', range: '0.2 - 1.2 mg/dl' },
    { name: 'DB', model: 'db', range: '0.0 - 0.4 mg/dl' },
    { name: 'Comments', model: 'comments' },
  ],
  UrineSwabForm: [
    { model: 'culture', name: 'Culture' },
    { model: 'epithelial_cells', name: 'Epithelial Cells' },
    { model: 'pus_cells', name: 'PUS Cells' },
    { model: 'vaginalis_cells', name: 'T. Vaginalis' },
    { model: 'rbc', name: 'RBC' },
    { model: 'cast', name: 'Cast' },
    { model: 'crystals', name: 'Crystals' },
    { model: 'parasites', name: 'Parasites' },
    { model: 'others', name: 'Others' },
    { name: 'Ciprofloxacin', model: 'ciprofloxacin' },
    { name: 'Rifampicin', model: 'rifampicin' },
    { name: 'Streptomycin', model: 'streptomycin' },
    { name: 'Azithromycin', model: 'azithromycin' },
    { name: 'Amoxicillin', model: 'amoxicillin' },
    { name: 'Erythromycin', model: 'erythromycin' },
    { name: 'Levofloxacin', model: 'levofloxacin' },
    { name: 'Gentamycin', model: 'gentamycin' },
    { name: 'Cefuroxime', model: 'cefuroxime' },
    { name: 'Ofloxacin', model: 'ofloxacin' },
    { name: 'Augmentin', model: 'augmentin' },
    { name: 'Peflacine', model: 'peflacine' },
    { name: 'Ceftazidime', model: 'ceftazidime' },
    { name: 'Ceporex', model: 'ceporex' },
    { name: 'Ceftriaxone', model: 'ceftriaxone' },
    { name: 'Comments', model: 'comments' },
  ],
  SemenAnalysisForm: [
    { name: 'Time Produced', model: 'time_produced' },
    { name: 'Time Received', model: 'time_received' },
    { name: 'Time of Analysis', model: 'time_of_analysis' },
    { name: 'Method of Production', model: 'method_of_production' },
    { name: 'Period of Abstinence', model: 'period_of_abstinence' },
    { name: 'Colour', model: 'colour' },
    { name: 'Viscosity', model: 'viscosity' },
    { name: 'Liquefaction', model: 'liquefaction' },
    { name: 'Spillname', model: 'spillname' },
    { name: 'Volume', model: 'volume' },
    { name: 'Odour', model: 'odour' },
    { name: 'PH', model: 'ph' },
    { name: 'Microscopy', model: 'microscopy' },
    { name: 'PUS Cells', model: 'pus_cells' },
    { name: 'RBC', model: 'rbc' },
    { name: 'Cellula Debris', model: 'cellula_debris' },
    { name: 'Spermatozoan', model: 'spermatozoan' },
    { name: 'Epithelial Cells', model: 'epithelial_cells' },
    { name: 'Percentage Motility', model: 'percentage_motility' },
    { name: 'Active', model: 'active' },
    { name: 'Sluggish', model: 'sluggish' },
    { name: 'Non-Progressive', model: 'non_progressive' },
    { name: 'Dead Cells', model: 'dead_cells' },
    { name: 'Morphology', model: 'morphology' },
    { name: '% Normal Cells', model: 'normal_cells' },
    { name: '% Abnormal Cells', model: 'abnormal_cells' },
    { name: 'Sperm Count', model: 'sperm_count' },
    { name: 'Others', model: 'others' },
    { name: 'Culture', model: 'culture' },
    { name: 'Appearance', model: 'appearance' },
    { name: 'Antibiotic Sensitivity' },
    { name: 'Ciprofloxacin', model: 'ciprofloxacin' },
    { name: 'Rifampicin', model: 'rifampicin' },
    { name: 'Streptomycin', model: 'streptomycin' },
    { name: 'Azithromycin', model: 'azithromycin' },
    { name: 'Amoxicillin', model: 'amoxicillin' },
    { name: 'Erythromycin', model: 'erythromycin' },
    { name: 'Levofloxacin', model: 'levofloxacin' },
    { name: 'Gentamycin', model: 'gentamycin' },
    { name: 'Cefuroxime', model: 'cefuroxime' },
    { name: 'Ofloxacin', model: 'ofloxacin' },
    { name: 'Augmentin', model: 'augmentin' },
    { name: 'Peflacine', model: 'peflacine' },
    { name: 'Ceftazidime', model: 'ceftazidime' },
    { name: 'Ceporex', model: 'ceporex' },
    { name: 'Ceftriaxone', model: 'ceftriaxone' },
    { name: 'Comments', model: 'comments' },
  ],
  SerumForm: [
    { model: 'total_ca', name: 'Total Ca+', range: '2.2 - 2.7 Mmol/L' },
    { model: 'uric_acid', name: 'Uric Acid', range: '2.4 - 7.0 mg/dL' },
    { model: 'po42', name: 'PO42+', range: '2.5 - 4.5 mg/dL' },
    { model: 'mg', name: 'Mg2+', range: '1.5 - 2.5 Mmol/dL' },
    { model: 'iron', name: 'Iron', range: '60 - 170 mcg/dl' },
    { model: 'tibc', name: 'TIBC', range: '240 - 450 mcg/dl' },
    { model: 'hb_ac', name: 'HB a/c', range: '4.0 - 5.6 %' },
    { model: 'ionized_ca', name: 'Ionized Ca2+', range: '1.2 - 1.4 Mmol/L' },
    { model: 'comments', name: 'Comments' },
  ],
  SEUCrForm: [
    { model: 'sodium', name: 'Na+', range: '128 - 160 Mmol/L' },
    { model: 'potassium', name: 'K', range: '3.5 - 5.5 Mmol/L' },
    { model: 'chlorine', name: 'CL', range: '97 - 108 Mmol/L' },
    { model: 'hco3', name: 'HCO3', range: '24 - 32 Mmol/L' },
    { model: 'urea', name: 'Urea', range: '10 - 55 Mmol/L' },
    { model: 'chromium', name: 'Cr', range: '0.7 - 1.4 Mmol/L' },
    { model: 'comments', name: 'Comments' },
  ],
  StoolAnalysisForm: [
    { model: 'culture', name: 'Culture' },
    { model: 'appearance', name: 'Appearance' },
    { model: 'pus_cells', name: 'PUS Cells' },
    { model: 'rbc', name: 'RBC' },
    { model: 'ova_cyst', name: 'OVA/Cyst' },
    { model: 'undigested_food_particles', name: 'Undigested Food Particles' },
    { model: 'schistoma_ova', name: 'Schistoma Ova' },
    { model: 'fob', name: 'FOB' },
    { model: 'others', name: 'Others' },
    { name: 'Ciprofloxacin', model: 'ciprofloxacin' },
    { name: 'Rifampicin', model: 'rifampicin' },
    { name: 'Streptomycin', model: 'streptomycin' },
    { name: 'Azithromycin', model: 'azithromycin' },
    { name: 'Amoxicillin', model: 'amoxicillin' },
    { name: 'Erythromycin', model: 'erythromycin' },
    { name: 'Levofloxacin', model: 'levofloxacin' },
    { name: 'Gentamycin', model: 'gentamycin' },
    { name: 'Cefuroxime', model: 'cefuroxime' },
    { name: 'Ofloxacin', model: 'ofloxacin' },
    { name: 'Augmentin', model: 'augmentin' },
    { name: 'Peflacine', model: 'peflacine' },
    { name: 'Ceftazidime', model: 'ceftazidime' },
    { name: 'Ceporex', model: 'ceporex' },
    { name: 'Ceftriaxone', model: 'ceftriaxone' },
    { name: 'Comments', model: 'comments' },
  ],
  UrinalysisForm: [
    { model: 'culture', name: 'Culture' },
    { model: 'appearance', name: 'Appearance' },
    { model: 'leukocytes', name: 'Leukocytes' },
    { model: 'protein', name: 'Protein' },
    { model: 'glucose', name: 'Glucose' },
    { model: 'blood', name: 'Blood' },
    { model: 'ph', name: 'PH' },
    { model: 'ascorbic_acid', name: 'Ascorbic Acid' },
    { model: 'urobilinogen', name: 'Urobilinogen' },
    { model: 'ketones', name: 'Ketones' },
    { model: 'gravity', name: 'S.gravity' },
    { model: 'bilirubin', name: 'Bilirubin' },
    { model: 'nitrite', name: 'Nitrite' },
    { model: 'others', name: 'Others' },
    { model: 'comments', name: 'Comments' },
  ],
  WidalReactionForm: [
    { name: 'Salmonella Typhi', oModel: 'salmonella_typhi_O', hModel: 'salmonella_typhi_H' },
    {
      name: 'S. Paratyphi A.',
      oModel: 'salmonella_paratyphia_AO',
      hModel: 'salmonella_paratyphi_AH',
    },
    {
      name: 'S. Paratyphi B.',
      oModel: 'salmonella_paratyphia_BO',
      hModel: 'salmonella_paratyphi_BH',
    },
    {
      name: 'S. Paratyphi C.',
      oModel: 'salmonella_paratyphia_CO',
      hModel: 'salmonella_paratyphi_CH',
    },
  ],
  BilirubinForm: [
    {
      name: '0 - 1 day',
      totalModel: 'total_zero_to_one_day',
      directModel: 'direct_zero_to_one_day',
      totalRange: '3.5 - 10.4 mg/dl',
      directRange: '0.0 - 0-4 mg/dl',
    },
    {
      name: '2 - 3 days',
      totalModel: 'total_two_to_three_days',
      directModel: 'direct_two_to_three_days',
      totalRange: '3.4 - 11.5 mg/dl',
      directRange: '0.0 - 0-4 mg/dl',
    },
    {
      name: '3 - 5 days',
      totalModel: 'total_three_to_five_days',
      directModel: 'direct_three_to_five_days',
      totalRange: '1.5 - 12.0 mg/dl',
      directRange: '0.0 - 0-4 mg/dl',
    },
    {
      name: 'Above 5 days',
      totalModel: 'total_above_five_days',
      directModel: 'direct_above_five_days',
      totalRange: '0.2 - 1.2 mg/dl',
      directRange: '0.0 - 0-4 mg/dl',
    },
    {
      name: 'Comments',
      totalModel: 'comments',
      directModel: '',
      totalRange: '',
      directRange: '',
    },
  ],
  HormonalAssayForm: [
    {
      name: 'FSH',
      model: 'fsh',
      ranges: [
        'Male: 2.0 - 14.0 mIU/ML',
        'Female:',
        'Follicular Phase: 2.0 - 10.0 mIU/ML',
        'Ovulatorial: 6.0 - 24.0 mIU/ML',
        'Luteal Phase: 1.5 - 8.0 mIU/ML',
        'Post Menopausal: 17.0 - 95.0 mIU/ML',
        'Pregnant Female: 0.0 - 11.6 mIU/ML',
      ],
    },
    {
      name: 'LH',
      model: 'lh',
      ranges: [
        'Male: 0.7 - 7.4 mIU/ML',
        'Female:',
        'Follicular Phase: 0.5 - 10.5 mIU/ML',
        'Mid Cycle: 18.4 - 61.2 mIU/ML',
        'Luteal Phase: 0.5 - 10.5 mIU/ML',
        'Post Menopause: 8.2 - 40.8 mIU/ML',
      ],
    },
    {
      name: 'Progesterone',
      model: 'progesterone',
      ranges: [
        'Child (1 - 10yrs): 0.07 - 0.52 ng/ml',
        'Male: 0.13 - 1.22 ng/ml',
        'Female:',
        'Follicular Phase: 0.15 - 1.40 ng/ml',
        'First Trimester: 7.25 - 90.0 ng/ml',
        'Luteal Phase: 2.0 - 25.0 ng/ml',
        'Second Trimester: 19.5 - 91.0 ng/ml',
        'Third Trimester: 49.0 - 422.0 ng/ml',
        'Post Menopausal: 0.0 - 0.80 ng/ml',
      ],
    },
    {
      name: 'Estradiol',
      model: 'estradiol',
      ranges: [
        'Male: 9.0 - 94.0 pg/ml',
        'Female:',
        'Follicular Phase: 9.0 - 175 pg/ml',
        'Periovulatory: 107 - 281 pg/ml',
        'Luteal Phase: 44.0 - 196 pg/ml',
        'Treated Menopausal: 42 - 289 pg/ml',
        'Unreated Menopausal: ND - 20 pg/ml',
        'Oral Contraceptives: ND - 103 pg/ml',
      ],
    },
    {
      name: 'Testosterone',
      model: 'testosterone',
      ranges: [
        'Boys Before Puberty: 0.1 - 3.7 ng/ML',
        'Male: 2.5 - 10.0 ng/ML',
        'Female: 0.2 - 0.95 ng/ML',
      ],
    },
    {
      name: 'Prolactin',
      model: 'prolactin',
      ranges: [
        'Post Menopausal: 1.5 - 18.5 ng/ML',
        'Adult Male: 1.8 - 17.0 ng/ML',
        'Adult Female: 1.2 - 19.5 ng/ML',
      ],
    },
    { name: 'PSA', model: 'psa', ranges: ['Healthy Males: (Less than 4.0)'] },
    {
      name: 'TSH',
      model: 'tsh',
      ranges: ['Low Normal: 0.28 - 0.53 uIu/ML', 'High Normal: 5.6 - 6.82 uIu/ML'],
    },
    { name: 'tT3', model: 'tT3', ranges: ['Expected Range: 0.52 - 1.85 ng/ML'] },
    {
      name: 'tT4',
      model: 'tT4',
      ranges: ['Male: 4.4 - 10.0 ug/ML', 'Female: 4.8 - 11.6 ug/ML'],
    },
    { name: 'Comments', model: 'comments', ranges: [] },
  ],
  FBCForm: [
    {
      name: 'WBC',
      model: 'wbc',
      childRange: '5 - 19',
      adultRangeMale: '3.3 - 10.0',
      adultRangeFemale: '3.4 - 9.8',
      unit: 'x10^3/ul',
    },
    {
      name: 'RBC',
      model: 'rbc',
      childRange: '3.9 - 5.3',
      adultRangeMale: '4.35 - 5.9',
      adultRangeFemale: '3.69 - 5.19',
      unit: 'x10^4/ul',
    },
    {
      name: 'HGB',
      model: 'hgb',
      childRange: '9.5 - 14.1',
      adultRangeMale: '13.7 - 16.7',
      adultRangeFemale: '11.7 - 14.5',
      unit: 'g/dl',
    },
    {
      name: 'HCT',
      model: 'hct',
      childRange: '30 - 40',
      adultRangeMale: '40.5 - 49.7',
      adultRangeFemale: '34.1 - 44.3',
      unit: '%',
    },
    {
      name: 'MCV',
      model: 'mcv',
      childRange: '70 - 84',
      adultRangeMale: '79.7 - 92.0',
      adultRangeFemale: '81.5 - 96.7',
      unit: 'fl',
    },
    {
      name: 'MCH',
      model: 'mch',
      childRange: '23 - 29',
      adultRangeMale: '26.1 - 33.3',
      adultRangeFemale: '26.5 - 33.5',
      unit: 'pg',
    },
    {
      name: 'MCHC',
      model: 'mchc',
      childRange: '31 - 35',
      adultRangeMale: '32.2 - 35.0',
      adultRangeFemale: '31.9 - 35.3',
      unit: 'g/dl',
    },
    {
      name: 'RDW',
      model: 'rdw',
      childRange: '11.6 - 14.4',
      adultRangeMale: '11.6 - 14.4',
      adultRangeFemale: '-',
      unit: '%',
    },
    {
      name: 'PLT',
      model: 'plt',
      childRange: '140 - 450',
      adultRangeMale: '140 - 450',
      adultRangeFemale: '-',
      unit: 'x10^3/ul',
    },
    {
      name: 'Neutrophils',
      model: 'neutrophils',
      childRange: '20 - 45',
      adultRangeMale: '45 - 66',
      adultRangeFemale: '-',
      unit: '%',
    },
    {
      name: 'Bands (Neutrophilic)',
      model: 'bands',
      childRange: '1 - 12',
      adultRangeMale: '1 - 12',
      adultRangeFemale: '-',
      unit: '%',
    },
    {
      name: 'Lymphocytes',
      model: 'lymphocytes',
      childRange: '46 - 76',
      adultRangeMale: '20 - 40',
      adultRangeFemale: '-',
      unit: '%',
    },
    {
      name: 'Atypical Lymphocytes',
      model: 'atypical_lymphocytes',
      childRange: '0 - 2',
      adultRangeMale: '0 - 2',
      adultRangeFemale: '-',
      unit: '%',
    },
    {
      name: 'Monocytes',
      model: 'monocytes',
      childRange: '1 - 5',
      adultRangeMale: '4 - 10',
      adultRangeFemale: '-',
      unit: '%',
    },
    {
      name: 'Eosinophils',
      model: 'eosinophils',
      childRange: '1 - 3',
      adultRangeMale: '1 - 6',
      adultRangeFemale: '-',
      unit: '%',
    },
    {
      name: 'Basophils',
      model: 'basophils',
      childRange: '0 - 2',
      adultRangeMale: '0 - 2',
      adultRangeFemale: '-',
      unit: '%',
    },
    {
      name: 'Anisocytosis',
      model: 'anisocytosis',
      childRange: '-',
      adultRangeMale: '-',
      adultRangeFemale: '-',
      unit: '',
    },
    {
      name: 'Microcytosis',
      model: 'microcytosis',
      childRange: '-',
      adultRangeMale: '-',
      adultRangeFemale: '-',
      unit: '',
    },
    {
      name: 'Macrocytosis',
      model: 'macrocytosis',
      childRange: '-',
      adultRangeMale: '-',
      adultRangeFemale: '-',
      unit: '',
    },
    {
      name: 'Hypochromia',
      model: 'hypochromia',
      childRange: '-',
      adultRangeMale: '-',
      adultRangeFemale: '-',
      unit: '',
    },
    {
      name: 'Poikliocytosis',
      model: 'poikliocytosis',
      childRange: '-',
      adultRangeMale: '-',
      adultRangeFemale: '-',
      unit: '',
    },
  ],
  OGTTForm: [
    { name: '0 min', model: 'ogtt_zero_min', range: '3.9 - 5.9 Mmol/L' },
    { name: '60 mins', model: 'ogtt_sixty_mins', range: '3.9 - 7.0 Mmol/L' },
    { name: '120 mins', model: 'ogtt_one_twenty_mins', range: '3.9 - 6.7 Mmol/L' },
    {
      name: 'Fasting',
      glucoseModel: 'urine_glucose_fasting',
      proteinModel: 'urine_protein_fasting',
    },
    {
      name: '60 mins',
      glucoseModel: 'urine_glucose_sixty_mins',
      proteinModel: 'urine_protein_sixty_mins',
    },
    {
      name: '120 mins',
      glucoseModel: 'urine_glucose_one_twenty_mins',
      proteinModel: 'urine_protein_one_twenty_mins',
    },
    {
      name: 'Others',
      glucoseModel: 'urine_glucose_others_mins',
      proteinModel: 'urine_protein_others_mins',
    },
  ],
};

// const tests = [
//   {
//     test: 'Fasting glucose',
//     results: [
//       {
//         name: 'Fasting glucose',
//         model: 'fasting_glu',
//         range: '5 - 5.8 Mmol/L',
//       },
//     ],
//   },
// ];
