<template>
  <div class="bill-filters">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-3">
            <b-form-group label="Patient Search" label-for="patient-search">
              <b-form-input
                id="patient-search"
                v-model="localFilters.patientName"
                placeholder="Search by patient name or ID..."
                @input="debounceSearch"
              >
                <template #prepend>
                  <i class="fas fa-search"></i>
                </template>
              </b-form-input>
            </b-form-group>
          </div>

          <div class="col-md-2">
            <b-form-group label="Bill Status" label-for="billing-status">
              <b-form-select
                id="billing-status"
                v-model="localFilters.billingStatus"
                :options="billingStatusOptions"
                @change="applyFilters"
              ></b-form-select>
            </b-form-group>
          </div>

          <div class="col-md-2">
            <b-form-group label="Payment Status" label-for="payment-status">
              <b-form-select
                id="payment-status"
                v-model="localFilters.paymentStatus"
                :options="paymentStatusOptions"
                @change="applyFilters"
              ></b-form-select>
            </b-form-group>
          </div>

          <div class="col-md-2">
            <b-form-group label="Date From" label-for="date-from">
              <b-form-input
                id="date-from"
                v-model="localFilters.dateFrom"
                type="date"
                @change="applyFilters"
              ></b-form-input>
            </b-form-group>
          </div>

          <div class="col-md-2">
            <b-form-group label="Date To" label-for="date-to">
              <b-form-input
                id="date-to"
                v-model="localFilters.dateTo"
                type="date"
                @change="applyFilters"
              ></b-form-input>
            </b-form-group>
          </div>

          <div class="col-md-1">
            <label>&nbsp;</label>
            <div class="d-flex gap-2">
              <b-button variant="outline-secondary" @click="clearFilters" title="Clear all filters">
                <i class="fas fa-times"></i>
              </b-button>
            </div>
          </div>
        </div>

        <!-- Advanced Filters Toggle -->
        <div class="advanced-filters-toggle">
          <b-button variant="link" @click="showAdvancedFilters = !showAdvancedFilters" class="p-0">
            <i :class="showAdvancedFilters ? 'fas fa-chevron-up' : 'fas fa-chevron-down'"></i>
            {{ showAdvancedFilters ? 'Hide' : 'Show' }} Advanced Filters
          </b-button>
        </div>

        <!-- Advanced Filters -->
        <div v-if="showAdvancedFilters" class="advanced-filters">
          <div class="row mt-3">
            <div class="col-md-3">
              <b-form-group label="Amount Range" label-for="amount-range">
                <b-form-input
                  id="amount-range"
                  v-model="localFilters.amountRange"
                  placeholder="Min - Max amount"
                  @change="applyFilters"
                ></b-form-input>
              </b-form-group>
            </div>

            <div class="col-md-3">
              <b-form-group label="Billing Mode" label-for="billing-mode">
                <b-form-select
                  id="billing-mode"
                  v-model="localFilters.billingMode"
                  :options="billingModeOptions"
                  @change="applyFilters"
                ></b-form-select>
              </b-form-group>
            </div>

            <div class="col-md-3">
              <b-form-group label="Created By" label-for="created-by">
                <b-form-select
                  id="created-by"
                  v-model="localFilters.createdBy"
                  :options="staffOptions"
                  @change="applyFilters"
                ></b-form-select>
              </b-form-group>
            </div>

            <div class="col-md-3">
              <b-form-group label="Auto-Generated" label-for="auto-generated">
                <b-form-select
                  id="auto-generated"
                  v-model="localFilters.autoGenerated"
                  :options="autoGeneratedOptions"
                  @change="applyFilters"
                ></b-form-select>
              </b-form-group>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'BillFilters',
  props: {
    filters: {
      type: Object,
      default: () => ({}),
    },
  },
  data() {
    return {
      showAdvancedFilters: false,
      localFilters: {
        patientName: '',
        billingStatus: '',
        paymentStatus: '',
        dateFrom: '',
        dateTo: '',
        amountRange: '',
        billingMode: '',
        createdBy: '',
        autoGenerated: '',
      },
      billingStatusOptions: [
        { value: '', text: 'All Bill Statuses' },
        { value: 'DRAFT', text: 'Draft' },
        { value: 'PENDING', text: 'Pending' },
        { value: 'APPROVED', text: 'Approved' },
        { value: 'REJECTED', text: 'Rejected' },
      ],
      paymentStatusOptions: [
        { value: '', text: 'All Payment Statuses' },
        { value: 'PENDING', text: 'Pending' },
        { value: 'PARTIAL', text: 'Partial' },
        { value: 'PAID', text: 'Paid' },
        { value: 'CANCELLED', text: 'Cancelled' },
      ],
      billingModeOptions: [
        { value: '', text: 'All Billing Modes' },
        { value: 'CASH', text: 'Cash' },
        { value: 'INSURANCE', text: 'Insurance' },
        { value: 'WAIVER', text: 'Waiver' },
        { value: 'OTHER', text: 'Other' },
        { value: 'FREE', text: 'Free' },
        { value: 'WALLET', text: 'Wallet' },
      ],
      staffOptions: [{ value: '', text: 'All Staff' }],
      autoGeneratedOptions: [
        { value: '', text: 'All Bills' },
        { value: 'true', text: 'Auto-Generated Only' },
        { value: 'false', text: 'Manual Only' },
      ],
    };
  },
  watch: {
    filters: {
      handler(newFilters) {
        this.localFilters = { ...this.localFilters, ...newFilters };
      },
      deep: true,
      immediate: true,
    },
  },
  methods: {
    debounceSearch: debounce(function() {
      this.applyFilters();
    }, 500),

    applyFilters() {
      // Amount range is handled in the parent component

      const filters = {
        patientName: this.localFilters.patientName,
        billingStatus: this.localFilters.billingStatus,
        paymentStatus: this.localFilters.paymentStatus,
        dateFrom: this.localFilters.dateFrom,
        dateTo: this.localFilters.dateTo,
        amountRange: this.localFilters.amountRange,
        billingMode: this.localFilters.billingMode,
        createdBy: this.localFilters.createdBy,
        autoGenerated: this.localFilters.autoGenerated,
      };

      this.$emit('filters-changed', filters);
    },

    clearFilters() {
      this.localFilters = {
        patientName: '',
        billingStatus: '',
        paymentStatus: '',
        dateFrom: '',
        dateTo: '',
        amountRange: '',
        billingMode: '',
        createdBy: '',
        autoGenerated: '',
      };
      this.applyFilters();
    },
  },
};

// Debounce utility function
function debounce(func, wait) {
  let timeout;
  return function executedFunction(...args) {
    const later = () => {
      clearTimeout(timeout);
      func(...args);
    };
    clearTimeout(timeout);
    timeout = setTimeout(later, wait);
  };
}
</script>

<style scoped>
.bill-filters {
  margin-bottom: 2rem;
}

.advanced-filters-toggle {
  text-align: center;
  margin-top: 1rem;
  padding-top: 1rem;
  border-top: 1px solid #e9ecef;
}

.advanced-filters {
  border-top: 1px solid #e9ecef;
  padding-top: 1rem;
}

.advanced-filters-toggle .btn-link {
  color: #6c757d;
  text-decoration: none;
}

.advanced-filters-toggle .btn-link:hover {
  color: #007bff;
}

@media (max-width: 768px) {
  .col-md-1,
  .col-md-2,
  .col-md-3 {
    margin-bottom: 1rem;
  }
}
</style>
