export default {
  payment: null,
  payments: [],
  total: null,
  pages: 0,

  accounts: [],
  accountsTotal: 0,
  accountsPages: 0,
  journalEntries: [],
  journalEntriesTotal: 0,
  journalEntriesPages: 0,
  financialStatements: null,
  costCenters: [],
  costCentersTotal: 0,
  costCentersPages: 0,
  departments: [],
  trialBalance: [],
  trendAnalysis: null,
  savedReports: [],
  loading: false,
  totalItems: 0,
  totalPages: 0,
  error: null,
};
